/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Calculate the diff between two files. */
export function diffFiles(a: string, b: string): Buffer
/** Calculate signature of a file. */
export function signature(src: string): Buffer
/** Calculate the diff between a file signature and the raw data. */
export function diff(signature: Buffer, buf: Buffer): Buffer
/** Apply */
export function patchFile(dest: string, delta: Buffer): Buffer
/** Apply */
export function apply(data: Buffer, delta: Buffer): Buffer
