/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Signature options. */
export interface SignatureOptions {
  /**
   * The granularity of the signature.
   * Smaller block sizes yield larger, but more precise, signatures.
   */
  blockSize: number
  /**
   * The number of bytes to use from the MD4 hash. Must be at most 16.
   * The larger this is, the less likely that a delta will be mis-applied.
   */
  cryptoHashSize: number
}
/** Calculate signature of a file. */
export function fileSignature(src: string): Buffer
/** Calculates a signature of a Buffer. */
export function signature(data: Buffer, options: SignatureOptions): Buffer
/** Calculate the diff between two files. */
export function diffFiles(a: string, b: string): Buffer
/** Calculate the diff between a file signature and the raw data. */
export function diff(signature: Buffer, buf: Buffer): Buffer
/** Apply the delta to a file. */
export function patchFile(dest: string, delta: Buffer): Buffer
/** Apply the delta to a Buffer. */
export function apply(data: Buffer, delta: Buffer): Buffer
